### ISSUE TITLE
"File no longer available" every time I launch a Luapad

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [rafcamlet/nvim-luapad#11]
Every time I invoke `:Luapad`, after a moment, I get an error like this:

> E211: File "~/.local/share/nvim/plugged/nvim-luapad/tmp/Luapad_2.lua" no longer available

Any idea what could be causing this, or how I could avoid it?

**Comment by rafcamlet** [comment]
Hi! Thanks for pointing this out.

Unfortunately that's an error in current implementation. I've fixed it in the dev branch. I have to do some more tests, and maybe I will be able to release a new version soon.

**Comment by rafcamlet** [comment]
@ELLIOTTCABLE The new version has been released. Please let me know if the problem is no longer present.
Have a nice day!
