### ISSUE TITLE
Plugin does not work at all if installed system-wide

### ISSUE THREAD

**Issue by KAction** [rafcamlet/nvim-luapad#12]
This definition of `path` function, which is used to generate path to temporary
lua file does not work if plugin is installed into system-wide (or, to be more
precise, in read-only) directory.

```
local function path(...)
  local str = debug.getinfo(2, "S").source:sub(2)
  root = str:match(("(.*)lua%sluapad.lua"):format(sep))
  return root .. table.concat({...}, (sep))
end
```

In which case `create_file` would raise error about `fd` being `nil`, since
`vim.loop.fs_open` returns (descriptor, error) pair, and returns nil descriptor
on failure.

```
local function create_file(f)
  local fd = vim.loop.fs_open(f, "w", 438)
  vim.loop.fs_close(fd)
end
```

Probably the simplest fix to the problem would be to use normal temporary
directory, random file name and 0600 file mode. I can make pull request with
these changes, and it will work on Unix. I have zero knowledge about Windows.

**Comment by rafcamlet** [comment]
@KAction Hi! Thanks for a detailed description of the problem. 👍 

There was already a PR for that (#10) Thanks @ck3d !
Eventually I had a while to test everything, and it even works on Windows. Everything should be fine now.
