### ISSUE TITLE
CursorHold issues

### ISSUE THREAD

**Issue by baodrate** [rafcamlet/nvim-luapad#18]
FYI, CursorHold is a bit bugged in neovim: https://github.com/neovim/neovim/issues/12587

There's [a plugin](https://github.com/antoinemadec/FixCursorHold.nvim) that fixes these issues. Since Luapad (partly) depends on CursorHold it might be a good idea to inform users about the issue and workaround.

**Comment by rafcamlet** [comment]
@qubidt That's a good idea. 👍 Thanks for pointing this out.
