### ISSUE TITLE
Move images in ./gifs folder to this issue

### ISSUE THREAD

**Issue by younger-1** [rafcamlet/nvim-luapad#19]
This can reduce the repo size significantly!

**Comment by rafcamlet** [comment]
I know there are few ways how to do that (pasting to markdown editor, creating issue with gifs or moving them to another branch). @younger-1 Do you have some suggestions which one is the best? Also thanks for pointing this out.

**Comment by younger-1** [comment]
I think most plugins put their image in issues (by just drag/patste image to github's markdown editor), which could be refer to as a showcase in the readme of plugin. And this may be the easiest way to manage multiple images!
