### ISSUE TITLE
Remove gifs/ next step.

### ISSUE THREAD

**Issue by ur4ltz** [rafcamlet/nvim-luapad#23]
To complete remove 'gifs/' Install [git-filter-repo](https://github.com/newren/git-filter-repo).
Copy this repository to new folders, and run this commands.

'''bash
git filter-repo --invert-paths --path gifs/ --force
'''

This command will remove gifs/ from history. I recommend doing it only with a copy of the repository!

**Comment by rafcamlet** [comment]
@ur4ltz Yes, it would be a nice addition, but is it really necessary? Package managers make shallow copies of repositories, so they don't care about history.

**Comment by ur4ltz** [comment]
Packer works differently than 'git clone --depth 1 <repo>' and the size stays the same.

**Comment by rafcamlet** [comment]
@ur4ltz So I checked this git-filter-repo, but unfortunately I can't use it. It rewrites history and changes commit hashes, which would trigger conflicts and consequently will prevent the plugin from being updated, forcing every user to figure out what happened and manually fixing it.

By default, packer uses shallow cloning. There is even a configuration option to specify the depth. But, yeah, there is a piece of code which is fetching the whole history when rollbacking the snapshot. I guess you were referring to that.

Either way, the gains don't match the losses in this case.
