### ISSUE TITLE
Have different highlight group for virtual text

### ISSUE THREAD

**Issue by kkharji** [rafcamlet/nvim-luapad#4]
Hay @rafcamlet  hope your doing great. 

Can we have an option for having a different highlight group for virtual text that comment?
I found out that some times I confuse virtual text with comments.

Thanks.

**Comment by rafcamlet** [comment]
Thx! A lot of work lately, but it's ok. :)

I've added an option to configure these highlights. They are described in the readme: https://github.com/rafcamlet/nvim-luapad#configuration

**Comment by kkharji** [comment]
@rafcamlet Thanks a lot 🙏
